export const GET_CONTACTS_REQUEST = "GET_CONTACTS_REQUEST";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE";

export const ADD_CONTACTS_REQUEST = "ADD_CONTACTS_REQUEST";
export const ADD_CONTACTS_SUCCESS = "ADD_CONTACTS_SUCCESS";

export const EDIT_CONTACTS_REQUEST = "EDIT_CONTACTS_REQUEST";
export const EDIT_CONTACTS_SUCCESS = "EDIT_CONTACTS_SUCCESS";

export const DELETE_CONTACTS_REQUEST = "DELETE_CONTACTS_REQUEST";
export const DELETE_CONTACTS_SUCCESS = "DELETE_CONTACTS_SUCCESS";